a=new Date();
console.log(a);
b=new Date();
console.log(b);
c=new Date(2000,04,21,04,15);
console.log(c);
d=new Date(2015,04,22);
console.log(d);
e=new Date(98,07,23);
console.log(e);
g=new Date("may 05,2015 12:30:00");
console.log(g);
console.log(Date.now());
k=new Date(1628224847787);
console.log(k);
i=new Date(2015,04,23);
console.log(i.toString());
//date string
j=new Date();
console.log(j.toDateString());
console.toString(j.toISOString());
h=new Date("may 22,2000");
console.log(Date.parse(h));
console.log(h.getDate());
console.log(h.getFullYear());
console.log(h.getMonth());
console.log(h.getMilliseconds());
e=(-5.5);
console.log(Math.log(e));
console.log(Math.round(e));
console.log(Math.ceil(e));
console.log(Math.floor(e));
console.log(Math.trunc(e));
console.log(Math.sign(e));
console.log(Math.pow(4,4));
console.log(Math.sqrt(81));
console.log(Math.abs(-22));
console.log(Math.tan(5));